### ISSUE TITLE
扫风和风力自定义发送指令

### ISSUE THREAD

**Issue by nutinshell** [mac-zhou/homeassistant-mi-acpartner#2]
这样可以方便的使用喜欢的扫风和风力。。

**Comment by 0xbw** [comment]
嗯，我主要是对homebridge-mi-acpartner的移植，看presets.json对扫风和风力也是比较简单。
所以有在考虑自定义

**Comment by 0xbw** [comment]
已经支持了，你可以更新一下测试看看

```yaml
climate:
  - platform: mi_acpartner
    name: mi_acpartner
    host: 10.0.0.234
    token: 1378a40b1a77ee7a8254b15c75cfb
    target_sensor: sensor.temperature_158d00015a
    # target_temp: 26
    # sync: 60
    customize:
      swing:
        test1: 12345
        test2: 67890
      fan:
        test3: 1122
        test4: 3344
        test5: 5566
```
test开头的是为操作指令名称，数字为自定义空调码
